# Generated by Django 4.1 on 2022-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='watched',
            field=models.TextField(),
        ),
    ]
