# Generated by Django 4.1 on 2022-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0005_alter_mywatchlist_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='release_date',
            field=models.CharField(max_length=15),
        ),
    ]
